### ISSUE TITLE
Add 'written by' field, implement possibility for multiple authors

### ISSUE THREAD

**Issue by jessesquires** [SwiftWeekly/swiftweekly.github.io#3]
Currently, would use `post.author` for the `written by` field. 

Written by:
- Appears below issue # and date, "Written by <Name of Author>"

Add authors to `_config.yml` ?

```
authors:
    jesse: 
        name: 'Jesse Squires'
        url: 'twitter.com/jesse_squires'
   john:
        name: 'john appleseed'
        url: 'twitter.com/johnappleseed'
```
